export const meta = {
  name: 'build-screens',
  description: 'Generate all React Native Paper (Material 3) screens for the QIK Anime mobile app',
  phases: [{ title: 'WriteScreens' }],
}

// Shared conventions embedded into every screen-writing agent.
const CONVENTIONS = `
You are writing ONE React Native screen file for the QIK Anime mobile app (Expo SDK 57, React Native 0.86, React 19). Target: \`mobile/src/screens/<NAME>.tsx\`.

STACK & VERSIONS (verified):
- react-native-paper v5 (Material 3 / MD3). Import components from 'react-native-paper'.
- @react-navigation/native v7, native-stack v7, bottom-tabs v7.
- @expo/vector-icons (MaterialCommunityIcons).
- expo-image for images, react-native-webview for embedded players, socket.io-client for WS.
- @react-native-async-storage/async-storage.

BEFORE WRITING, READ THESE FILES to get EXACT signatures (do not guess):
- mobile/src/api/backend.ts  (QIK backend client — all functions)
- mobile/src/api/yummy.ts    (YummyAnime client — api, fixUrl, poster, upgradePoster)
- mobile/src/api/client.ts   (request, uploadUrl, getToken)
- mobile/src/components/Screen.tsx, AnimeCard.tsx, Poster.tsx, Avatar.tsx, States.tsx, SectionHeader.tsx
- mobile/src/hooks/useApi.ts
- mobile/src/context/AuthContext.tsx, ThemeContext.tsx
- mobile/src/navigation/AppNavigator.tsx (RootStackParamList — your screen's params)
- mobile/src/utils/layout.ts (cardWidth, SCREEN_WIDTH)

AVAILABLE SHARED PIECES (use them; do not reinvent):
- \`import Screen from '../components/Screen'\` — props: { children, refreshing?, onRefresh?, padded? }. Wraps content in safe-area + a scrollable FlatList with pull-to-refresh. Put your screen body as children. For screens that manage their own scroll (long lists/grids), you MAY use a plain ScrollView/FlatList with SafeAreaView + useSafeAreaInsets instead of <Screen>.
- \`import AnimeCard from '../components/AnimeCard'\` — props: { item, onPress, width? }.
- \`import Poster from '../components/Poster'\` — props: { uri, style, contentFit? }. Handles static.yani.tv -> imgproxy fallback automatically.
- \`import Avatar from '../components/Avatar'\` — props: { user, size? }.
- \`import { LoadingState, ErrorState, EmptyState } from '../components/States'\` — ErrorState{message,onRetry}, EmptyState{icon,message,action,actionLabel}.
- \`import SectionHeader from '../components/SectionHeader'\` — { title, actionLabel?, onAction? }.
- \`import { useApi } from '../hooks/useApi'\` — useApi(fetcher, deps) -> { data, loading, error, refetch }.
- \`import { useAuth } from '../context/AuthContext'\` — { user, openAuthModal, addToast(msg,type), logout, refreshUser, ... }.
- \`import { useThemeCtx } from '../context/ThemeContext'\` — { theme, isDark, toggleTheme, setTheme }.
- \`import { useTheme } from 'react-native-paper'\` — Paper MD3 theme. Use theme.colors.{primary,onPrimary,surface,surfaceContainer,surfaceContainerHigh,onSurface,onSurfaceVariant,background,outline,outlineVariant,error,...}. roundness=14.
- \`import { cardWidth, SCREEN_WIDTH } from '../utils/layout'\`.
- Navigation: \`import { NativeStackScreenProps } from '@react-navigation/native-stack'\` and \`import { RootStackParamList } from '../navigation/AppNavigator'\`. Define \`type Props = NativeStackScreenProps<RootStackParamList, 'SCREENNAME'>\`. Use \`const { navigation, route } = props\` / \`navigation.navigate('AnimeDetail', { id, title })\`. If a screen is a tab, it has no route param — use \`useNavigation<NativeStackNavigationProp<RootStackParamList>>()\` from '@react-navigation/native' instead, and import type { NativeStackNavigationProp }.

DESIGN RULES (Material 3):
- Use Paper components: Button (mode 'contained'|'outlined'|'text'|'elevated'), Card, Text (variant 'titleLarge'|'bodyMedium'|...), TextInput (mode 'outlined'), List.Item, IconButton, Divider, Chip/SegmentedButtons, Avatar, Surface, FAB, Searchbar, ActivityIndicator, Banner, Menu, Dialog/Portal, Badge, ProgressBar, ToggleButton.Group, Snackbar not needed (global).
- Cards on theme.colors.surfaceContainer, borderRadius 14, padding 12. Section spacing 16.
- All user-facing text in RUSSIAN.
- Use StyleSheet.create. Keep it clean and responsive (numColumns grids via cardWidth).
- Handle loading/error/empty states via the shared components.
- For auth-required actions when user is null: call openAuthModal() from useAuth instead of crashing.
- Poster extraction: prefer api.poster(item) or item.posterUrl / item.poster_url; AnimeCard already extracts posters, so pass raw YummyAnime items to AnimeCard.
- For grids use FlatList with numColumns and keyExtractor. For horizontal rails use FlatList horizontal.

VIDEO (only Watch & RoomWatch): use react-native-webview. For HLS (.m3u8) build an HTML string with hls.js loaded from CDN (https://cdn.jsdelivr.net/npm/hls.js@latest) inside a <video> and inject via WebView originWhitelist=['*']. For iframe/embed URLs (kodik etc.) render the URL directly in WebView. Save watch progress via backend.saveProgress.

OUTPUT: Use the Write tool to create the file at the EXACT path given. Write complete, self-contained, compilable TypeScript/TSX. Do not leave TODOs or placeholders. After writing, return a single line: "WROTE <path> (<approx-line-count> lines)" — nothing else. If you cannot use Write, return the full file content wrapped in <FILE path="...">...</FILE>.
`

const SCREENS = [
  { name: 'HomeScreen', spec: `Home tab. Fetch api.feed() (YummyAnime) and (if logged in) backend.continueWatching(). UseApi both. Layout: a top app bar row (Surface) with title "QIK Anime", a search IconButton -> navigation.navigate('Search'), and a notifications IconButton -> navigation.navigate('Notifications'). Then horizontal rails: if user -> "Продолжить просмотр" rail of continue-watching items (poster + episode label, onPress navigate AnimeDetail). Then sections from the feed (the feed returns arrays like ongoing/franchises/recommendations/etc. — iterate whatever keys exist and render SectionHeader + horizontal AnimeCard rail). Tap any card -> navigation.navigate('AnimeDetail', { id: item.id || item.alias, title: item.title || item.ru_title }). Use Screen with onRefresh=refetch.` },
  { name: 'CatalogScreen', spec: `Catalog tab. Fetch api.catalog() once for filter metadata (genres, types, years, seasons) and api.list(params) for the grid with pagination. params: { limit, page, genres[], type, status, season, order }. State: filters, page, items[], loadingMore. UI: a Searchbar at top (onSubmit navigate('Search', {q})). A horizontal scroll of Chips: type (tv/movie/ova/...), status, year, and a few genre chips from catalog. A FlatList grid (numColumns 3, cardWidth(3)) of AnimeCard. Infinite scroll: onEndReached increments page and appends. Pull to refresh resets. Tap -> AnimeDetail.` },
  { name: 'LibraryScreen', spec: `Library tab (bookmarks). If !user: render EmptyState (icon 'bookmark-off-outline', message "Войдите, чтобы видеть свою библиотеку", action openAuthModal, actionLabel "Войти"). Else: SegmentedButtons for status: watching/planned/completed/on_hold/dropped (labels: Смотрю/В планах/Просмотрено/Отложено/Брошено). Fetch backend.listBookmarks(activeStatus) via useApi keyed on status. Grid (numColumns 3) of AnimeCard built from bookmark items (bookmark has animeId, title, posterUrl, episodesWatched, status). Each card onPress -> AnimeDetail {id: bookmark.animeId}. Long-press a card -> Menu to remove bookmark (backend.removeBookmark(animeId)) or change status.` },
  { name: 'ProfileScreen', spec: `Profile tab. If !user: EmptyState login (openAuthModal). Else fetch backend.profile(user.id) via useApi. Show: banner (expo-image, uploadUrl(bannerUrl)) behind, Avatar (size 96) overlapped, username, bio, level badge + XP (profile returns level, xp, stats). Stats row: episodes watched, total seconds (format hours), comments, bookmarks, friends. Achievements row (profile.achievements array -> Chip or grid of emoji+name). Avatar frames availability. A header right IconButton 'pencil' -> navigation.navigate('EditProfile'); a 'dots-vertical' Menu with: Настройки->Settings, Друзья->Friends, Чаты->Chats, Уведомления->Notifications, Комнаты->Rooms, Квиз->Quiz, Баг-трекер->Issues (only if user.role is master or admin), Админка->Admin (only if admin), and Выйти->logout(). Below: a SegmentedButtons tab switch among "Статистика / Закладки / История / Друзья". Статистика: genre breakdown (backend.genreBreakdown) as Bars or Chips. Закладки: backend.userBookmarks(user.id) grid. История: backend.watchHistory(user.id) list. Друзья: backend.userFriends(user.id) list (Avatar + username, tap -> navigate to that user's profile by id; since no separate user-profile screen, just show). Use Screen with onRefresh=refetch.` },
  { name: 'AnimeDetailScreen', spec: `Route params { id, title? }. Fetch api.anime(id) (YummyAnime, use route.params.id), backend.getBookmark(id), backend.getRating(id), backend.listComments(id), api.recommendations(id) — use useApi with relevant deps. UI: hero poster + backdrop, title (ru + original), genres Chips, score, status/episodes/year/studio metadata, description (expandable via Text numberOfLines toggle). Action row: a big "Смотреть" Button -> navigation.navigate('Watch', {id, title}). A Bookmark menu Button (IconButton 'bookmark' / 'bookmark-plus') opening a Menu to set status (watching/planned/completed/on_hold/dropped/favorite) via backend.upsertBookmark, or remove via backend.removeBookmark; reflect current bookmark status. Rating widget: a 1-10 selector (SegmentedButtons or a row of star Buttons) via backend.rate / removeRating. OP/ED ratings: backend.getOpeningRatings(id) -> two rows (Opening/Ending) each a 1-10 picker via backend.rateOpening({animeId,type,score}) type 'opening'|'ending'. Comments section: list comments (Avatar, username, body, likes count, time), add comment TextInput + send Button (backend.addComment {animeId, body}), like IconButton (backend.likeComment), and delete (own comments, backend.deleteComment). Recommendations: horizontal AnimeCard rail. Use a ScrollView (not Screen) because the page is long; wrap in SafeAreaView.` },
  { name: 'WatchScreen', spec: `Route params { id, title? }. Fetch api.videos(id) (YummyAnime) -> returns players/episodes structure (array of episodes, each with players/dubs). UI: episode selector (horizontal Chips or List), dubbing/player selector. Selected video source: if a player provides an HLS .m3u8 URL, render a react-native-webview with an HTML page embedding hls.js from CDN (https://cdn.jsdelivr.net/npm/hls.js@latest) playing the stream in a <video controls>. If a player provides an iframe/embed URL (e.g. kodik), render that URL directly in WebView. Show a 16:9 WebView. Track progress: on WebView navigationStateChange or via injected JS polling current time, call backend.saveProgress({animeId:Number(id), episode, second, duration, title, poster}). Use backend.progressForAnime(id) to resume. Provide episode prev/next buttons. Use Screen-like layout (SafeAreaView).` },
  { name: 'RatingsScreen', spec: `Route param optional { tab? }. Four subtabs via SegmentedButtons: Аниме (backend.topAnime), Опенинги (backend.topOpenings), Эндинги (backend.topEndings), Пользователи (backend.topUsers). Fetch the active one via useApi keyed on activeTab. Render a ranked List: position number, for anime: poster thumb + title + average rating; for openings/endings: anime title + type + score; for users: Avatar + username + level/xp. Use List.Item with rank Badge. Screen + onRefresh.` },
  { name: 'ScheduleScreen', spec: `Fetch api.schedule() (YummyAnime). Returns schedule grouped by weekday. UI: SegmentedButtons or a horizontal day tab (Пн..Вс). For the selected day, a List of releases (poster thumb, title, episode number). Tap -> AnimeDetail. Screen + onRefresh.` },
  { name: 'SearchScreen', spec: `Route param optional { q? }. A Searchbar. On submit: backend.saveSearch(q) (best-effort, ignore errors) and fetch api.search(q, { limit: 24, page }) via useApi keyed on query+page. When query empty: show backend.searchHistory() as removable Chips/list (delete via backend.deleteSearch, clear all via backend.clearSearchHistory); tapping a history item runs that search. Results: grid (numColumns 3) of AnimeCard -> AnimeDetail. Infinite scroll by page. Screen.` },
  { name: 'FriendsScreen', spec: `Fetch backend.listFriends() and backend.pendingFriends() via useApi. UI: Pending requests section (incoming) with Accept (backend.acceptFriend) / Decline (backend.removeFriend). Friends list: Avatar + username, tap -> (no user-profile screen) open a Menu: Написать (backend.startChat(friendId) -> navigation.navigate('ChatThread',{chatId,title:username})), Удалить (backend.removeFriend). A search bar to find users (backend.searchUsers(q)) showing results with an "Добавить" button (backend.requestFriend). Screen + onRefresh.` },
  { name: 'NotificationsScreen', spec: `Fetch backend.notifications() via useApi. On mount call backend.markAllRead() then refetch (best-effort). Render a List of notifications: leading icon by type (friend_request, friend_accept, anime_suggestion, comment_reply, system), body text, time. Swipe or IconButton to delete (backend.removeNotification). EmptyState when none. Screen + onRefresh.` },
  { name: 'ChatsScreen', spec: `Fetch backend.listChats() via useApi. List of chats: Avatar of the other participant, username, last message preview, time, unread badge if present. Tap -> navigation.navigate('ChatThread', { chatId: chat.id, title: otherUsername }). FAB or header button to start a chat from friends (navigate Friends). EmptyState when none. Screen + onRefresh.` },
  { name: 'ChatThreadScreen', spec: `Route params { chatId, title? }. Fetch backend.chatMessages(chatId) via useApi. Render messages as bubbles (own messages right-aligned primary container, others left surface). Poll for new messages every 5s with a useEffect interval calling refetch (compare length to avoid jumps — simple refetch is fine). Bottom: TextInput + send IconButton -> backend.sendChatMessage(chatId, { body }) then clear and refetch. Use KeyboardAvoidingView. SafeAreaView. Set header title to route.params.title.` },
  { name: 'RoomsScreen', spec: `Watch rooms (auth required; if !user -> EmptyState login). Fetch backend.listWatchRooms() via useApi. UI: active rooms list (room code, owner, participants count, current anime title). "Создать комнату" Button -> backend.createWatchRoom({}) then navigation.navigate('RoomWatch', { roomId: room.id }). "Войти по коду" -> a Dialog/TextInput for code -> backend.joinWatchRoom(code) -> navigate RoomWatch { roomId }. Tap a room -> RoomWatch { roomId }. Screen + onRefresh.` },
  { name: 'RoomWatchScreen', spec: `Route params { roomId }. Fetch backend.watchRoom(roomId) via useApi. Connect to WebSocket: io('https://quickik.ru/watch-rooms', { transports:['websocket'], auth: { token: await getToken() } }) from 'socket.io-client'; import { getToken } from '../api/client'. Emit 'room:join' { roomId }. Listen 'room:snapshot','room:state','room:members','room:message'. UI: a video area (react-native-webview) playing the room's current video (AniLibria HLS via hls.js HTML, or the room.video url). Host controls: play/pause/seek buttons -> backend.updateWatchRoomState(roomId, { playing, time, ... }) which broadcasts. Search AniLibria (backend.searchAnilibria(q)) and set video (backend.setWatchRoomVideo(roomId, payload)). Chat: messages list + input -> backend.sendWatchRoomMessage(roomId, { body }); incoming 'room:message' appended. Members list. Leave button (backend.leaveWatchRoom) -> navigation.goBack. Clean up socket on unmount. SafeAreaView. This screen is complex — keep the WS + chat + player working; host sync via HTTP PATCH is fine.` },
  { name: 'SettingsScreen', spec: `Settings. Use useThemeCtx for a theme toggle (Switch or SegmentedButtons: Тёмная/Светлая -> setTheme). Show app version "1.0.0". Links rows (List.Item) to: EditProfile, Friends, Notifications, Rooms, Quiz. A row to Issues (if master/admin) and Admin (if admin) — check useAuth().user.role. About row with backend info (best-effort backend.adminServer() only if admin, else static). Logout Button (useAuth().logout). Screen.` },
  { name: 'EditProfileScreen', spec: `Route none (from Profile). Prefill from useAuth().user. Fields: username (TextInput), bio (TextInput multiline), avatarColor (a row of color swatches to pick), avatarFrame (dropdown/Chips of available frames: none/Mint/Lavender/Peach/Rose/Gold/Aurora/Legend). Avatar upload: a Button "Сменить аватар" -> expo-image-picker launchImageLibraryAsync({mediaTypes:'images',allowsEditing:true,aspect:[1,1]}) -> if result.assets[0] -> backend.uploadImage({ uri, name, type:'image/jpeg' }) -> set avatarUrl preview. Same for banner ("Сменить баннер", aspect [16,9]). Save Button -> backend.updateProfile({ username, bio, avatarColor, avatarFrame, avatarUrl, bannerUrl }) then useAuth().refreshUser() + addToast + navigation.goBack. Screen/SafeAreaView. import * as ImagePicker from 'expo-image-picker'.` },
  { name: 'QuizScreen', spec: `Emoji/anime quiz. Mode toggle (SegmentedButtons): "Угадай аниме" (backend.quizQuestion) vs "Эмодзи" (backend.quizEmoji). State: current question, score, answered, exclude[] of seen ids. Fetch a question via useApi-less useEffect (manual fetch). Show question text/emoji + answer options as Buttons. On answer: highlight correct/incorrect, increment score if right, push id to exclude, then "Далее" Button fetches next question (with exclude). Track score and rounds. Screen/SafeAreaView.` },
  { name: 'IssuesScreen', spec: `Bug tracker (masters/admins only; if user.role not master/admin -> EmptyState "Недостаточно прав"). Fetch backend.listIssues(statusFilter) via useApi keyed on status. SegmentedButtons filter: all/open/in_progress/done (map to ''/open/in_progress/done). List of issues: title, status Chip, assignee. Create: a FAB/Button -> Dialog with TextInput title -> backend.createIssue(title). Tap an issue -> a Dialog/expanded view: change status (Menu -> backend.updateIssue), assign to self (backend.assignIssue), add attachment (expo-image-picker -> backend.uploadAttachment(issueId, file)), list attachments with delete (backend.deleteAttachment), delete issue (backend.deleteIssue). Screen + onRefresh.` },
  { name: 'AdminScreen', spec: `Admin panel (admins only; if user.role !== 'admin' -> EmptyState "Недостаточно прав"). Fetch backend.adminStats() and backend.adminUsers() via useApi. Stats cards: total users, masters count, anime count, bookmarks, comments, etc. (render whatever stats returns as a grid of stat tiles). Users table: List of users (Avatar, username, email, role Chip) with actions: toggle master (backend.adminToggleMaster) via Switch or IconButton, delete user (backend.adminDeleteUser) with confirmation Dialog. A "Стать админом" claim flow if not admin: TextInput for ADMIN_SECRET -> backend.adminClaim(secret) -> refreshUser. Search users by query param. Screen + onRefresh. Keep destructive actions behind confirm Dialogs.` },
]

phase('WriteScreens')

const results = await parallel(
  SCREENS.map((s) => () =>
    agent(
      CONVENTIONS + `\n\n=== YOUR SCREEN: ${s.name} ===\nFile path: mobile/src/screens/${s.name}.tsx\nSpec: ${s.spec}\n\nUse the Write tool to create the file now. Return one line: "WROTE <path> (<n> lines)".`,
      { label: s.name, phase: 'WriteScreens', agentType: 'general-purpose' },
    ),
  ),
)

const summary = results.map((r, i) => ({ screen: SCREENS[i].name, result: r })).filter(Boolean)
log(`Done. ${summary.length} agents returned.`)
return { summary }
